# Generated by Django 4.1.1 on 2022-11-18 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import medapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Elder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDN', models.CharField(max_length=13)),
                ('first_name', models.CharField(max_length=30)),
                ('sure_name', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('memory', models.JSONField()),
                ('image', models.ImageField(blank=True, upload_to=medapp.models.user_directory_path)),
                ('face', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TakeCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('careTaker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('elder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.elder')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.JSONField()),
                ('lunch', models.JSONField()),
                ('dinner', models.JSONField()),
                ('night', models.JSONField()),
                ('elder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.elder')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('med_picture', models.ImageField(upload_to='')),
                ('elder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.elder')),
            ],
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_number', models.CharField(max_length=30)),
                ('hospital_name', models.CharField(max_length=50)),
                ('hospital_phone', models.CharField(max_length=10)),
                ('relative_firstname', models.CharField(max_length=30)),
                ('relative_surename', models.CharField(max_length=30)),
                ('relative_relation', models.CharField(max_length=30)),
                ('relative_phone', models.CharField(max_length=10)),
                ('elder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.elder')),
            ],
        ),
        migrations.CreateModel(
            name='ElderPhysical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical', models.JSONField()),
                ('elder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.elder')),
            ],
        ),
        migrations.CreateModel(
            name='ElderDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.JSONField()),
                ('elder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.elder')),
            ],
        ),
    ]
